### ISSUE TITLE
Add an option to clear the deploy directory on deploy

### ISSUE THREAD

**Issue by spacey-sooty** [wpilibsuite/deploy-utils#24]
The way I see it this could be done here with something a prop which could look something like.
```sh
./gradlew deploy -Pdestructive
```
This could also be done with a seperate task to wipe artifacts currently on the roboRIO, something like
```sh
./gradlew clearrio
```

**Comment by PeterJohnson** [comment]
How to do it in your own build.gradle if desired is a 1-line change: https://www.chiefdelphi.com/t/clearing-the-deploy-directory-on-a-roborio-running-commands-on-the-roborio/458273/10?u=peter_johnson

**Comment by spacey-sooty** [comment]
Maybe a good idea to document that somewhere as I've seen a lot of teams asking about it
