### ISSUE TITLE
No Signature of method deploy

### ISSUE THREAD

**Issue by CJBuchel** [wpilibsuite/deploy-utils#9]
Platforms
[linuxx86-64 & windowsx86-64]
[DeployUtils: 2022.3.0]

I've been bashing my head against my keyboard because of this for a while.
I have some custom coprocessor code that I have been using for the last few years. The building method has been a mix of makefiles and gradlerio depending on the platform. But the deploying method has usually been Embedded tools. Until now due to the jcenter deprecation making it nearly impossible to use Embedded tools as a plugin. 

So I've switched to deploy-utils as that seems to be WPI's main method for deploying. And seems like a decent idea as everything would be officially supported. However, something has happened recently which has made the existing deployable code not work.

I'm not deploying binaries over for various reasons, just filetrees and files. Along with using pre/post deploy methods for simple scripts. So it's not linked to any type of binary artifact.

The weirdest thing is, the examples for creating coprocessor deploys is exactly the same. I'm not sure what's missing from the deploy.

Essentially i have.
```gradle
deploy {
  targets {
      target('coprocessor') {
        directory = '/home/vision/'
        maxChannels = 1
        timeout = 3
        failOnMissing = true

        locations {
          ssh {
            address = "CJVision.local"
            user = 'vision'
            password = 'CJfrc'
            ipv6 = false
          }
        }

      }
    }
    
    artifacts {
      // Common properties
      all {
        targets << 'coprocessor'
        dependsOn('build')
        predeploy << {
          if (project.hasProperty('purge')) {
            execute('sudo rm -r *')
            execute('echo 0000 | sudo tee /home/vision/team')
          }
        }
      }
      
      fileTreeArtifact("cjVision_main") {
        directory = "$device_cjVision_src/main"
        files = fileTree(dir: "cj_vision_dir/main")
      }
      
      ...
   }
   
   
}
```

Do you have any ideas why it's no longer working?
I have a suspicion that it has something to do with not having a model linked to it anymore. As that is the only difference between the coprocessor code and the roborio deploy code. A single line like `deployArtifact.component = it`. Not saying it is this line, but it's pretty much the only difference between the two.

Any help would be appreciated. Below is also the error message if it helps, but it looks like a standard `something is missing` error to me, without saying what it missing.
```
No signature of method: deploy_dqkn0v7j6ryiascm3tzesg4nj.deploy() is applicable for argument types: (deploy_dqkn0v7j6ryiascm3tzesg4nj$_run_closure1) values: [deploy_dqkn0v7j6ryiascm3tzesg4nj$_run_closure1@33791bfc]
  Possible solutions: apply(groovy.lang.Closure), apply(java.util.Map), every(), copy(groovy.lang.Closure), copy(org.gradle.api.Action), delete([Ljava.lang.Object;)
```

**Comment by ThadHouse** [comment]
Currently the jcenter downtime is temporary, so it should come back soon, which should allow you to keep using the old plugin. If you wait a day or 2 it should be fixed on gradles side.

EmbeddedTools because DeployUtils, and was rewritten to be much easier to maintain. Part of this included a major change to the dsl and the deploy block. I didn't update the examples (ran out of time) so technically they won't work either, I'm on vacation right now, but when I get back I can whip up an example how to do what you want.

The other option is the Readme was updated, so you should be able to copy from there. The binary artifacts in there are not important, and can be deleted. I should add some comments in there explaining the blocks.

**Comment by CJBuchel** [comment]
Thanks,
I went through the readme but it didn't seem to help my case. But it's alright, the issue isn't major at the moment and I can wait the few days for things to get working again on gradle side. 

Plus Jaci said she'd give me a hand probably tomorrow and see if she can figure out what I'm doing wrong.
So eventually I expect things will work out. That being said an example when you get back from vacation would be much appreciated.

Until then I'll probably brush up on my gradle plugin knowledge and try sift through the java files to see what I've misplaced.
Enjoy your vacation.

**Comment by ThadHouse** [comment]
Did you try updating to the new style in the readme? What you posted in your post was how embedded tools worked. New 2022 gradlerio projects also use the updated deploy utils. You can easily tell because the artifacts block is inside the target block in the new style, whereas what you posted has the artifact block outside.

**Comment by CJBuchel** [comment]
I did try updating to the newer method. As much as possible, using the readme as a reference point along with how the roborio gets deployed. Although the error message is generally the same so I couldn't tell if I was getting warmer or colder to the proper syntax.

Below is what I've tried
```gradle
deploy {
  targets {
    target(getLocationTypeClass('coprocessor')) {
    
       directory = '/home/vision/'
        maxChannels = 1
        timeout = 3
        failOnMissing = true

        locations {
          ssh {
            address = "CJVision.local"
            user = 'vision'
            password = 'CJfrc'
            ipv6 = false
          }
        }
        
        artifacts {
          all {
            dependsOn('build')
          }
        }
    }
  }
}
```

I've also been switching bits and pieces out trying to see which section is wrong. I.e, like the getLocationTypeClass which i stumbled through in java.

**Comment by ThadHouse** [comment]
`coprocessor(getTargetTypeClass('RemoteTarget')` is what you want. The first part is the name, and the second part is the type of target you want. It's opposite of what the old style is.

**Comment by CJBuchel** [comment]
Oh I see, when I read the comment in the readme about the name I didn't take it literal enough. 
Thanks, the code seems to be building now.

**Comment by ThadHouse** [comment]
Cool, glad it worked out. Let me know if you need any more help. It's a lot more normal gradle now, which should make things easier.

**Comment by CJBuchel** [comment]
I could use one bit of extra help if you have the time.
For the `ssh {}` block I'm finding a hard time figuring out what type it needs. (I see SshDeployLocations being the one). I assume similar to the target it would have some kind of `get` method to make it simple. Like `getTargetTypeClass()`. But I can't figure out what the method should be.

**Comment by ThadHouse** [comment]
Hmm. Assuming you're in the root project, you can use the import and then just use SshDeployLocation like the readme shows. I forgot to add a helper for that if you're in a subproject.  I can add one when I get back, it's an easy patch.

**Comment by CJBuchel** [comment]
Ah, alright. Thought I was going insane there for a second when I couldn't find the method. That's fine, this is a root project for the moment. It will have some hassles later on when I try to chuck this into a mutlproject gradle workload like with our robot. But I figure I can do some majiggering to get it to work a few weeks from now.

Thanks a bunch.

**Comment by ThadHouse** [comment]
Since theres been no update, and it seems like most things were solved, I'm going to close this. If something comes along feel free to open a new issue.
